GOOSE_PROVIDER: openai
GOOSE_MODEL: claude-sonnet-4-20250514-v1-project
extensions:
  developer:
    enabled: true
    name: developer
    type: builtin
  
  autovisualiser:
    enabled: false
    type: "builtin"
    bundled: true
  
  pipeline:
    enabled: true
    name: dsagt
    type: stdio
    cmd: dsagt-pipeline-server
    timeout: 300
    
  registry:
    enabled: true
    name: registry
    type: stdio
    cmd: dsagt-registry-server
    timeout: 300

  knowledge:
    enabled: true
    name: knowledge
    type: stdio
    cmd: dsagt-knowledge-server
    timeout: 300
GOOSE_MODE: approve
